apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - image: stevenaraka/udagram-api-feed:v2
        name: udagram-api-feed
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "200m"       
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: env-config-map
      restartPolicy: Always