language: node_js
node_js:
  - 13


services:
  - docker


# Pre-testing installs
install:
  - echo "nothing needs to be installed"


# Scripts to be run such as tests
before_script:
  - echo "no tests"


# Building services & tagging services
script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-api-feed stevenaraka/udagram-api-feed:v2
  - docker tag udagram-api-user stevenaraka/udagram-api-user:v3
  - docker tag udagram-reverseproxy stevenaraka/udagram-reverseproxy:v2
  - docker tag udagram-frontend stevenaraka/udagram-frontend:v2

# Push images
# Assuming DOCKERHUB_PASSWORD and DOCKERHUB_USERNAME are set in the Travis repository settings
after_success:
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

  - docker push stevenaraka/udagram-api-feed:v2
  - docker push stevenaraka/udagram-api-user:v3
  - docker push stevenaraka/udagram-reverseproxy:v2
  - docker push stevenaraka/udagram-frontend:v2
