apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api-user
  template:
    metadata:
      labels:
        app: udagram-api-user
    spec:
      containers:
      - image: stevenaraka/udagram-api-user:v4
        name: udagram-api-user
        resources:
          requests:
            memory: "400Mi"
          limits:
            memory: "800Mi"
        args: ["--vm", "1", "--vm-bytes", "600M", "--vm-hang", "1"]
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: env-config-map
              key: postgres_host
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: env-config-map
              key: postgres_db
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env-config-map
              key: aws_bucket
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: env-config-map
              key: aws_region
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: env-config-map
              key: aws_profile
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: env-config-map
              key: jwt_secret
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-config-map
              key: url